-- 메리츠캐피탈 샘플 데이터
INSERT INTO company_details (
  company_name,
  product_types,
  website_link,
  kakao_link,
  id_pw,
  email,
  fax,
  address,
  phone,
  delivery_company,
  construction_industry,
  insurance_change_after_contract,
  domestic_import_available,
  liability_limit,
  rent_import_insurance_age,
  lease_pledge,
  deductible,
  license_guarantee,
  deposit_account,
  succession_fee,
  new_corporation,
  screening_funding,
  age_limit,
  overdue_interest_rate,
  foreigner,
  driver_range,
  mileage_excess,
  drunk_reacquired_under_1year,
  early_termination_penalty,
  family_driver_condition,
  total_loss,
  handling_restrictions,
  account_name_change
) VALUES (
  '메리츠캐피탈',
  ARRAY['장기렌트', '리스'],
  'https://open.kakao.com/o/g9GyNcBh',
  'https://open.kakao.com/o/g9GyNcBh',
  '참여코드: star1234',
  '담당자 이혜진 대리 02-2017-7208, leehyejin@meritz.co.kr / 조명숙차장 010-7419-7989, ms.cho@meritz.co.kr',
  '0505-005-7244',
  '서울특별시 서초구 강남대로39길 15-10, 한라비발디193, 상가2층 204호',
  '대표 1588-9666 / 사고정비 1577-0565 / 승계문의 02-3462-6602',
  '현대·쉐보레·르노·테슬라 선보, 기아·쌍용 동운로지스',
  '주행거리 3만KM 이내 가능, 무제한 X',
  '불가',
  '국산 렌트·리스 가능, 수입 렌트 테슬라만 가능, 리스는 견적기 입력 시 가능',
  '1억 ~ 3억',
  '만 26세',
  '총차량가',
  '10만원, 20만원, 30만원',
  '진행불가',
  '우리 1005-004-257004 메리츠캐피탈(주)',
  '구간별 30~100만원',
  '진행가능',
  '전자약정 프로세스',
  '렌트 만26~75세, 리스 무제한',
  '연 24%',
  '진행가능',
  '개인/개사/법인 케이스별 규정',
  '렌트 3천km, 리스 2천km, 초과 200원',
  '불가능',
  '규정 20%, 중도해지 85%',
  '운전경력 1년 이상',
  '중도해지 수수료율 + 면책금',
  '업데이트 예정',
  '직계가족만 가능'
);

-- KB캐피탈 샘플 데이터
INSERT INTO company_details (
  company_name,
  product_types,
  website_link,
  kakao_link,
  id_pw,
  phone,
  deductible,
  rent_import_insurance_age,
  age_limit,
  domestic_import_available,
  lease_pledge,
  license_guarantee,
  new_corporation,
  screening_funding,
  driver_range,
  mileage_excess,
  foreigner,
  early_termination_penalty,
  delivery_company,
  account_name_change
) VALUES (
  'KB캐피탈',
  ARRAY['장기렌트', '리스'],
  'https://kbeasy.kbcapital.co.kr/ss/mm/MM010100.kbc#noback',
  'https://open.kakao.com/o/gkMnVSQc',
  '참여코드: 1004',
  '대표 1544-7100',
  '국산 30만원, 수입 50만원',
  '만 26세',
  '국산 렌트 만24~74세, 수입 렌트 만26~74세',
  '국산·수입 렌트·리스 광범위 가능',
  '총차량가',
  '관계·증빙 규정 및 업로드 지침',
  '보증·서류 요건 상세',
  '전자약정 범위, 개인/법인/공동대표 등 케이스별 서류',
  '개인, 임직원 특약 케이스별',
  '렌트 1천km, 초과 200원',
  '진행가능',
  '약정기간별 수치 제공',
  '유림로지텍, HL홀딩스',
  '배우자·직계가족 계좌 연결 가능'
);

-- 우리카드 샘플 데이터
INSERT INTO company_details (
  company_name,
  product_types,
  website_link,
  kakao_link,
  email,
  phone,
  delivery_company,
  liability_limit,
  rent_import_insurance_age,
  lease_pledge,
  deductible,
  license_guarantee,
  deposit_account,
  succession_fee,
  new_corporation,
  screening_funding,
  age_limit,
  overdue_interest_rate,
  foreigner,
  driver_range,
  mileage_excess,
  drunk_reacquired_under_1year,
  early_termination_penalty,
  family_driver_condition,
  total_loss,
  account_name_change
) VALUES (
  '우리카드',
  ARRAY['리스'],
  'https://open.kakao.com/o/gqkEW5nh',
  'https://m.wooricard.com/dcmw/yh1/mmb/mmb01/M1MMB201S00_AG.do',
  'sjyang@wooricard.com',
  '대표 1544-9800 / 사고정비 1644-1199 / 승계문의 1544-9800',
  '삼익, 유림, 선보 등',
  '1억 ~ 3억',
  '수입차 불가',
  '총차량가',
  '10만원, 20만원, 30만원, 50만원',
  '진행불가',
  '우리 2881-156-9118710 (주)우리카드, 최대 60%',
  '20만원 ~ 100만원',
  '진행가능',
  '전자약정 개인/개사 가능, 법인 불가',
  '만21세 ~ 70세 이하',
  '연 24%',
  '불가능',
  '개인/개사/법인 규정',
  '렌트 1천km, 초과 100~300원',
  '진행불가',
  '기간 구간별 30~20%',
  '경력 1년 이상',
  '위약금 발생',
  '직계가족만 가능'
);

-- 신한카드 샘플 데이터
INSERT INTO company_details (
  company_name,
  product_types,
  website_link,
  phone,
  deductible,
  rent_import_insurance_age,
  age_limit,
  domestic_import_available,
  lease_pledge,
  license_guarantee,
  new_corporation,
  screening_funding,
  driver_range,
  mileage_excess,
  foreigner,
  early_termination_penalty,
  delivery_company,
  account_name_change
) VALUES (
  '신한카드',
  ARRAY['장기렌트', '리스'],
  'https://mycar.shinhancard.com/adp/ADPFM860N/ADPFM860R20.shc',
  '대표 1544-7100 / 사고정비 1544-7751 / 승계문의 1544-7100',
  '국산 30만원, 수입 50만원',
  '만 26세',
  '국산 렌트 만24~74세, 수입 렌트 만26~74세',
  '광범위 가능. 렌트 스포츠카 불가, 리스 가능',
  '총차량가',
  '관계·증빙 규정 및 업로드 지침',
  '보증·서류 요건 상세',
  '전자약정 범위, 개인/법인/공동대표 등 케이스별 서류',
  '개인, 임직원 특약 케이스별',
  '렌트 1천km, 초과 200원',
  '진행가능',
  '약정기간별 수치 제공',
  '유림로지텍, HL홀딩스',
  '배우자·직계가족 계좌 연결 가능'
);
